name: CI/CD Workflow

# Trigger the workflow on push to feature branches and main branch
on:
  push:
    branches:
      - 'main'
      - 'feature/*'  # Adjust this based on your feature branch naming convention

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Using Node.js version 20 as referred from other workflows

      - name: Install dependencies using pnpm
        run: |
          corepack enable
          pnpm install

      - name: Run tests
        run: pnpm test

  deploy:
    # Deploy only on main branch
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies using pnpm
        run: |
          corepack enable
          pnpm install

      - name: Build project
        run: pnpm run build

      - name: Deploy to production
        run: |
          echo "Deployment step here."
          # Add your deployment script here

  release:
    # Release only on push to main branch
    if: github.ref == 'refs/heads/main'
    needs: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: 'Release ${{ github.sha }}'
          body: |
            ## Release Notes
            - Auto-generated release for commit ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub provides this
